# coding: utf-8
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_NO_COLOR'] = 'true'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "dockerhost", autostart: true, primary: true do |dockerhost|
    dockerhost.vm.box = "ubuntu/xenial64"
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    dockerhost.vm.network "forwarded_port", guest: 8500, host: 8500 # consul/consul-ui
    dockerhost.vm.network "forwarded_port", guest: 8200, host: 8200 # vault/vault-ui

    dockerhost.vm.provision "docker" do |docker|
    end  

    dockerhost.vm.provision "shell", keep_color: false, run: "always", path: "dockerhost/provision.sh"
    
    $post_up_message = <<POST_UP
If you see this message it means your Vagrant VM is ready to go.

$ vagrant ssh
$ sudo su -
# cd /vagrant && make

Enjoy!
POST_UP
    
    dockerhost.vm.post_up_message = $post_up_message
  end
end
